name: CloudVoxel Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint project
        run: bun run lint

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run tests
        run: bun run test
